export enum MarkerType {
    Other = 'other',
    SiteOfGrace = 'siteofgrace',//賜福
    shortPath = 'shortpath',//捷徑
    wayGates = 'waygates',//傳送門
    RuneFarm = 'runefarm',//刷魂點
    Shop = 'shop',
    NPC = 'npc',
    Location = 'location',//地點
    SummoningPool = 'summoningpool',//多人連線點
    Cave = 'cave',//洞窟
    HorseTorrent = 'horsetorrent',//靈魂氣流
    WalkingMausoleum = 'walkingmausoleum',//漫步靈廟
    BigBoss = 'bigboss',//大Boss
    Boss = 'boss',//一般boss
    LittleBoss = 'littboss',//小boss
    NPCInvaders = 'npcinvaders',//紅靈入侵
    GreatEnemy = 'greatenemy',//菁英怪
    Item = 'item',//物品
    Cartacombs = 'cartacombs', //地下墓地
    Evergaol = 'evergaol',//封印監牢
    GoldenSeed = 'goldenseed',//黃金種子
    CrystalTears = 'crystaltears',//露滴
    Keyitems = 'keyitems',//重要物品
    StoneSwordKey = 'stoneswordkey',//石劍鑰匙
    DeathRoot = 'deathroot',//死根
    DragonHeart = 'dragonheart',//龍心臟
    LarvalTear = 'larvaltear',//淚滴幼體
    PickersBellBearing = 'pickersbellbearing',//墓地鈴蘭
    SacredTear = 'sacredtear', //聖杯露滴
    MinersBellBearing = 'minersbellbearing',//礦工玲珠
    Gesture = 'gesture',//動作
    Painting = 'painting',//畫
    Material = 'material',//資源
    Sorceries  = 'sorceries',//魔法
    Weapon = 'weapon',//武器
    Cookbook = 'cookbook',//製作筆記
    Whetblade = 'whetblade',//砥石刀
    Incantation = 'incantation',//禱告
    Tailsman = 'tailsman',//護符
    AshOfWar = 'ashofwar',//戰灰
    SpiritAsh = 'spiritash',//骨灰
    Armor = 'armor',//裝備
    Text = 'text',
    Warn = 'warn',
    Question = 'question',
    Taoke = 'taoke',
}