
const Locations = [
    {
        id:2,
        enname:'SiteOfGrace',
        zhname:'賜福點'
    },
    {
        id:3,
        enname:'ShortPath',
        zhname:'捷徑'
    },
    {
        id:4,
        enname:'Waygates',
        zhname:'傳送門'
    },
    {
        id:5,
        enname:'RuneFarm',
        zhname:'刷魂點'
    },
    {
        id:17,
        enname:'Cartacombs',
        zhname:'地下墓地'
    },
    {
        id:18,
        enname:'Evergaol',
        zhname:'封印監牢'
    },
    {
        id:6,
        enname:'Shop',
        zhname:'商店'
    },
    {
        id:7,
        enname:'NPC',
        zhname:'NPC'
    },
    {
        id:8,
        enname:'SummoningPool',
        zhname:'連線點'
    },
    {
        id:10,
        enname:'WalkingMausoleum',
        zhname:'漫步靈廟'
    },
    {
        id:9,
        enname:'HorseTorrent',
        zhname:'靈魂氣流'
    },
 ]
 const Enemy = [
    {
        id:11,
        enname:'BigBoss',
        zhname:'大Boss'
    },
    {
        id:12,
        enname:'Boss',
        zhname:'Boss'
    },
    {
        id:13,
        enname:'LittleBoss',
        zhname:'小Boss'
    },
    {
        id:14,
        enname:'NPCInvaders',
        zhname:'紅靈入侵'
    },
    {
        id:15,
        enname:'GreatEnemy',
        zhname:'菁英怪'
    },
 ]

 const Items = [
    {
        id:16,
        enname:'Item',
        zhname:'物品'
    },
    {
        id:52,
        enname:'MAP',
        zhname:'地圖碎片'
    },
    {
        id:34,
        enname:'Cookbook',
        zhname:'製作筆記'
    },
    {
        id:35,
        enname:'Whetblade',
        zhname:'砥石刀'
    },
    {
        id:19,
        enname:'GoldenSeed',
        zhname:'黃金種子'
    },
    {
        id:20,
        enname:'CrystalTears',
        zhname:'露滴'
    },
    {
        id:21,
        enname:'KeyItems',
        zhname:'重要物品'
    },
    {
        id:22,
        enname:'StoneSwordKey',
        zhname:'石劍鑰匙'
    },
    {
        id:23,
        enname:'DeathRoot',
        zhname:'死根'
    },
    {
        id:24,
        enname:'DragonHeart',
        zhname:'龍心臟'
    },
    {
        id:25,
        enname:'LarvalTear',
        zhname:'淚滴幼體'
    },
    {
        id:30,
        enname:'Painting',
        zhname:'畫'
    },
    // {
    //     id:26,
    //     enname:'PickersBellBearing',
    //     zhname:'墓地鈴蘭'
    // },
    {
        id:27,
        enname:'SacredTear',
        zhname:'聖杯露滴'
    },
    {
        id:29,
        enname:'Gesture',
        zhname:'動作'
    },
    {
        id:31,
        enname:'Material',
        zhname:'資源'
    },
    //---------------
    {
        id:28,
        enname:'BellBearing',
        zhname:'鈴珠'
    },
    {
        id:51,
        enname:'GraveGlovewort',
        zhname:'墓地鈴蘭'
    },
    {
        id:46,
        enname:'GravePickerBellBearing',
        zhname:'鈴蘭鈴珠'
    },
    {
        id:47,
        enname:'GhostGlovewort',
        zhname:'靈依鈴蘭'
    },
    {
        id:48,
        enname:'GhostPickerBellBearing',
        zhname:'靈依鈴珠'
    },
    {
        id:51,
        enname:'SmithingStone',
        zhname:'鍛造石'
    },
    {
        id:49,
        enname:'SmithingBellBearing',
        zhname:'鍛造石鈴珠'
    },
    {
        id:50,
        enname:'SomberBellBearing',
        zhname:'失色石鈴珠'
    },
    {
        id:52,
        enname:'SomberSmithingStone',
        zhname:'失色石'
    }
 ]
 const Equipments = [
    {
        id:33,
        enname:'Weapon',
        zhname:'武器'
    },
    {
        id:40,
        enname:'Armor',
        zhname:'防具'
    },
    {
        id:37,
        enname:'Tailsman',
        zhname:'護符'
    },
    {
        id:36,
        enname:'Incantation',
        zhname:'禱告'
    },
    {
        id:32,
        enname:'Sorceries',
        zhname:'魔法'
    },
    {
        id:38,
        enname:'AshOfWar',
        zhname:'戰灰'
    },
    {
        id:39,
        enname:'SpiritAsh',
        zhname:'骨灰'
    },
 ]
 const Other = [
    {
        id:1,
        enname:'Other',
        zhname:'其他'
    },

]

export { Locations, Enemy, Items, Equipments, Other }